window.fileLinksMap = {
    "แนวทางการเขียนรายงานวิจัย ปฐมวัย.pdf":  "1BMgcqTkxTFRJ7wfdmL7Gl07k30u8SG-y",
    "รวมเล่ม ลุก รับ เรียน รู้.pdf":  "115GFwx0F3q6yIJak16aDwZxzOXZGZfar",
    "รวมบทความอัตนัย 2563.pdf":  "1QuYdBChfLUV1-_k6la-WTQbH-zaUnYap",
    "รวมบทความการประเมินแบบบูรณาการเพื่อรองรับ CBE.pdf":  "1-nMltR42RSysPcS8FxDiaIRwBUOwq0ae",
    "รวมบทความ Learning Loss.pdf":  "1b6jzDlgGM0oHB7mqVSUaGAqsWATGf40j",
    "รวมเล่ม 10 เทคนิค GPT.pdf":  "1WwhpSd2ybisccJ6tmiAlZupF5JMlcP1E",
    "รวมบทความการวัดผลแบบบูรณาการข้ามศาสตร์.pdf":  "1_P61_JoJhllYo2UzpXXyBWLO-LhINZRr",
    "รวมบทความ PA final.pdf":  "1JFXy-rU-boGRuwg3cjOes9fEkfYE9A8O",
    "รวมเล่ม NT คณิตศาสตร์ 63 64 65.pdf":  "1uqxLUvp7XXXmf-Ia2nmdXRJdg76P-Oqx",
    "รวมเล่ม ChatGPT for Supervisor.pdf":  "1940AQg9OFnoEGOZUSBsjOkiIJPTqcc46",
    "รวมเล่มวิจัยในชั้นเรียนสถานการณ์ที่ไม่คุ้นเคย.pdf":  "167Xs8kfEndMf6b-uztYj5Ntz9V_iTpSS",
    "รวมเล่มบันทึกใน FB.pdf":  "13FsiVUl7nCrM3VleVzeNrvnjtaNowolw",
    "รวมเล่ม ChatGPT for Teacher.pdf":  "12Ceyt1h4rOOhkDif7fjJDf1hj35Q12F7",
    "รวมเล่มความเชื่อมโยงวิจัยในชั้นเรียน และ ระดับวิทยฐานะ.pdf":  "11C2g0Slzb4E65_kuDTwBFq3KYRUUhBLW",
    "รวมเล่ม visual rubrics final.pdf":  "1zmEH7Y-vT1SfNcMDsZhghRIULCF8yLeu",
    "รวมเล่ม ChatGPT for Student.pdf":  "17O_Rg2idcMca_F3Okl8X1CpzTjIPDsRr",
    "รวมเล่มแนวทางการเขียนรายงานการวิจัยในชั้นเรียน เอกชน.pdf":  "1yZ9J5n2UV18HXF4wn4r1aRAhSbpxp1wO",
    "รวมเล่ม LDS v.2.pdf":  "1hll-I1CUJs5Q3-4ocd9wuzkHzl1UoGs2",
    "รวมบทความอัตนัย 2564.pdf":  "17-7ZZPPm9NsEAo0ccMxp632cHOF-EUq8",
    "รวมเล่ม Canva v 2.pdf":  "13Xa1gl_uNn2x84ey6ahy6T1WtNcvzYEo",
    "รวมเล่ม onet 65 66 67.pdf":  "1-8ZrWiau7wtDxfbtohvbGPhmkDS8_Er9",
    "รวมเล่ม ChatGPT for director.pdf":  "19ecLgpehweqBH9lBUDOu_uQwmHDrJc2R",
    "รวมบทความอัตนัย 2562.pdf":  "1Bjaa-qVj6AryBAPHrpLmy4Gf1HI3gSwx",
    "รวมเล่มรายงาน NT 2561.pdf":  "16X0q6ZSFrJFdnJnNzhrzZJz3F_MBngVo",
    "รวมเล่มทบทวนความรู้การวิจัยในชั้นเรียน.pdf":  "1h6lM9LJ6QHIj31nlzsFUUyO9kb17WCWk",
    "รวมเล่มรายงาน Onet 2566.pdf":  "15vgks11IbN7xU5dzEfUixtybEi1OBbpK",
    "รวมเล่มวัดผลบูรณาการ.pdf":  "1fxjUnlmsbgvN0Vy0uVAxl1cZ-BnX5yJx",
    "รวมเล่ม 10 ปี A5.pdf":  "1clWvEeC3vLco3APVfsQ01MAx_HF_1ol0",
    "รวมเล่ม Innovator to innovation final.pdf":  "1FlkXLSgXo1PH7ZGP3QnX2L90BxLi-bHp",
    "รวมเล่มรายงานการบริหารการสอบ onet 2563.pdf":  "1LQf0A-bkPKNG-hLDkqQ8eeEt490p_RtF",
    "รวมเล่มการวิเคราะห์มาตรฐานการเรียนรู้เอกชน ท้องถิ่น 2566.pdf":  "1EHwhIrm_oGpNpqmonCTvl3CS-qdX5JeR",
    "รวมเล่ม AL 2568.pdf":  "11gWOIl3gx11wcLCTHHKL-KQfS5CNY0cq",
    "รวมเล่ม GDS.pdf":  "1dMfzsuUxz51zSxXgOFDtHfbmVR3SfpU6",
    "รวมเล่มการประเมินในสถานการณ์ที่ไม่คุ้นเคย.pdf":  "19zPNOndf695Gym8NKGRFRA4LqtNg8YJN",
    "รวมเล่ม active local modern final.pdf":  "194-m9fcX8aDnv7MARv3R90at9cWnFA8Q",
    "รวมเล่มนิเทศการณ์ ปก 5.pdf":  "1HtFhdNXTHBcI8rbKVxAblVAcLJ8qK5cj",
    "รวมเล่ม ChatGPT กับการวัดผลในชั้นเรียน.pdf":  "1JmXxrl8EU_6-SJTd-wEWyluQczsjJyDk",
    "รวมเล่มรายงาน ท 2.1 2566.pdf":  "1XbxQ8CYN3PTUj3sM0n3jsAh1hM-mfhjY",
    "รวมเล่ม NT ภาษาไทย 63 64 65.pdf":  "1sIeVXRkJDI2-tETw6_GqbwpCGM-AGli4",
    "รวมบทความอัตนัย 2566.pdf":  "1COPfTOCwdIZg24XRwbRzB85-ZnCWYo1m",
    "รวมเล่มนานาทัศนะ final.pdf":  "1DdhMsAeusl82N08dr0tnOy2DT92HGQ4_",
    "รวมเล่ม AI for science final.pdf":  "1JEXw0qbUbYcTxEvGCBy96CkiH8A1Eg2R",
    "แนวทางการเขียนรายงานวิจัย ขั้นพื้นฐาน.pdf":  "1La97L4mP2dgjGeImAz91Jm8vJqREBhJN",
    "รวมเล่มกิจกรรมพัฒนาพหุปัญญา ป.4-ป.6 ครูสร้าง final.pdf":  "1C89zOgFcKrpwsqOvCxbdU-uGJS4gMxXi",
    "รวมเล่มตัวชี้วัด Onet 2565.pdf":  "1VgXmxWU1_DwY7xkoXU_dOaFojDXV55TE",
    "รวมเล่ม education taxonomy final.pdf":  "1Pn2sLxuu1ka3nyQ4xYXUgFnzuEVdctwZ",
    "รวมเล่ม data driven education.pdf":  "1sEd1Y4hkvfjKO9XN5CS1VtSHiqK5adRD",
    "รวมเล่ม ChatGPT for parent.pdf":  "17kg7NrQxbFlaIIUhFDLVjh94gHU0Rs4X",
    "รวมบทความการเขียนข้อสอบชนิดเขียนตอบ อัตนัย.pdf":  "1zN37dZ74an81cAM6nGFO1jriB34KIiWi",
    "รวมเล่มเปรียบเทียบมาตรฐานการเรียนรู้ 2565.pdf":  "1FlK1v3_c2QhW-fH473g-U4qHzUOWZm_t"
};